### ISSUE TITLE
Connecting a DC source to a transformer 

### ISSUE THREAD

**Issue by PAla46** [Proto-App/Proto-Android#153]
Sometimes when I connect a DC source to a step up transformer, it increases the output voltage eventhough transformers do not work with DC voltage

**Comment by YukarinnAM** [comment]
actually
transformers seems to actually works thanks to current
because of they made out of inductors
so when you use a voltage source without any resistence, it'll simply charge up infinitly because it doesn'y have a limit current and it'll keep increasing, hence having a Fluctuation
I think is a common problem with all virtually ideal transformers
i would recomment using a small resistor to simulate a real transformer one
Getting technical transformer can work in dc, but only for a very very very very brief moment because of this current limit thingy
i know is not really my problem but if i can help
well, i do i guess(?
