### ISSUE TITLE
Scope Analyze Function

### ISSUE THREAD

**Issue by standardE** [Proto-App/Proto-Android#218]
I'm having a very hard time figuring out how to use the scope. Whenever I try to analyze more than one attribute at a time it seems that the second attribute gets inverted. For example, in this circuit below, I expect current and voltage to rise together and fall together as the power supply voltage changes. But instead, one trace always inverts. Am I not using something correctly?
![Screenshot_20230404-130217_P R O T O](https://user-images.githubusercontent.com/39847113/229865473-e6d30315-e83f-4db4-b557-5d4e8af5a394.jpg)

**Comment by Proto-App** [comment]
Hi @standardE 
You use it correctly. Scope shows opposite values because we have to measure somehow current via wire. In this example current has negative value because PROTO can not decide which point of a wire is a "reference" point. You can delete wire from example and place new one from R3 (first point) to R4. First point is a refrenece point to measure and you will get positive value that matches voltage changes.

**Comment by standardE** [comment]
Ahh! Ok, I will mess around with that. I figured it was just some little detail that I didn't know. Thanks!
