### ISSUE TITLE
Copied component attaches to existing 

### ISSUE THREAD

**Issue by KarlW100** [Proto-App/Proto-Android#37]
When a component is copied, depending on where the displayed circuit might be, it will be placed on top of an existing point attaching itself to the circuit. It cannot be moved without dragging the existing wires. The program should check before placing to see if it's going on existing points, or include a button to detach a component.

**Comment by Proto-App** [comment]
Thank you for report, we will try to check if another terminal is present on grid.

**Comment by Proto-App** [comment]
At first attempt we will try to check for existing terminals on circuit grid. Solution like dragging components from the panel sounds great! But from technical point of view it is hard because left panel is a native Android view component and circuit grid is very fast OpenGL surface and this feature requires some connection between two different views.
