### ISSUE TITLE
Insufficient workspace dimensions

### ISSUE THREAD

**Issue by Raart** [Proto-App/Proto-Android#66]
After playing around with Proto, I experienced that if I will come to more complicated circuits there is a serious workspace problem.
Symbol dimensions are too wide to fit onto the workspace.
Please add greater virtual space and/or pinch/zoom to change scale ratio to get the correct visual and workspace needed.

**Comment by Proto-App** [comment]
@Raart 
Do you have any suggestion about workspace size? We can not make it unlimited. Bigger workspace can introduce performance bottleneck in some cases (slower phones)

**Comment by Ashwin-droid** [comment]
Yes, you cant make unlimited workspace beforehand (nothing is unlimited!!) 
But there is a exception,
if you reach the end of your workspace, It will render another 3-5 blocks of space on that side so that on powerful phones The space is virtually limitless 
And on old phones they have to limit it (Anyways the space was limited in the first place)


FREE Optimizing trick :  Remove the unused blocks ( like if the circuit is going on the side, you can unrender (free up memory) top and bottom blocks ) this method will save memory exponentially as circuit complexes
